
server:
  servlet:
    context-path: /freedom/common
  port: 10000
spring:
  freemarker:
    charset: UTF-8
  data:
    jpa:
      repositories:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password: rootroot
    url: jdbc:mysql://localhost:3306/freedom?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      allow-pool-suspension: true




